local LOCATION_MAPPING = {

    [0x1] = {"@Main/Shopsanity/Purchase Small Shield Brecconary", 
			 "@Main/Shopsanity/Purchase Small Shield Kol"},
    [0x2] = {"@Main/Shopsanity/Purchase Large Shield Garinham", 
			 "@Main/Shopsanity/Purchase Large Shield Cantlin"},
    [0x3] = {"@Main/Shopsanity/Purchase Silver Shield Cantlin"},
    [0x4] = {"@Main/Shopsanity/Purchase Clothes Brecconary"},
    [0x8] = {"@Main/Shopsanity/Purchase Leather Armor Brecconary", 
			 "@Main/Shopsanity/Purchase Leather Armor Garinham", 
			 "@Main/Shopsanity/Purchase Leather Armor Cantlin"},
    [0xC] = {"@Main/Shopsanity/Purchase Chain Mail Garinham", 
			 "@Main/Shopsanity/Purchase Chain Mail Cantlin"},
    [0x10] = {"@Main/Shopsanity/Purchase Half Plate Kol", 
			  "@Main/Shopsanity/Purchase Half Plate Garinham", 
			  "@Main/Shopsanity/Purchase Half Plate Rimuldar"},
    [0x14] = {"@Main/Shopsanity/Purchase Full Plate Kol", 
			  "@Main/Shopsanity/Purchase Full Plate Rimuldar", 
			  "@Main/Shopsanity/Purchase Full Plate Cantlin"},
    [0x18] = {"@Main/Shopsanity/Purchase Magic Armor Rimuldar", 
			  "@Main/Shopsanity/Purchase Magic Armor Cantlin"},
    [0x20] = {"@Main/Shopsanity/Purchase Bamboo Pole Brecconary", 
			  "@Main/Shopsanity/Purchase Bamboo Pole Cantlin"},
    [0x40] = {"@Main/Shopsanity/Purchase Club Brecconary", 
			  "@Main/Shopsanity/Purchase Club Garinham", 
			  "@Main/Shopsanity/Purchase Club Cantlin"},
    [0x60] = {"@Main/Shopsanity/Purchase Copper Sword Brecconary", 
			  "@Main/Shopsanity/Purchase Copper Sword Kol", 
			  "@Main/Shopsanity/Purchase Copper Sword Garinham", 
			  "@Main/Shopsanity/Purchase Copper Sword Rimuldar", 
			  "@Main/Shopsanity/Purchase Copper Sword Cantlin"},
    [0x80] = {"@Main/Shopsanity/Purchase Hand Axe Kol", 
			  "@Main/Shopsanity/Purchase Hand Axe Garinham", 
			  "@Main/Shopsanity/Purchase Hand Axe Rimuldar", 
			  "@Main/Shopsanity/Purchase Hand Axe Cantlin"},
    [0xA0] = {"@Main/Shopsanity/Purchase Broad Sword Rimuldar", 
			  "@Main/Shopsanity/Purchase Broad Sword Cantlin",},
    [0xC0] = {"@Main/Shopsanity/Purchase Flame Sword Cantlin"},
    [0xDD] = {"@Main/Charlock Castle/Defeated Dragonlord"},
    [0xFF] = {"@Main/world_map/Rainbow Shrine"},
    [0xD02] = {"@Main/Levelsanity/Level 2-9"},
    [0xD03] = {"@Main/Levelsanity/Level 2-9"},
    [0xD04] = {"@Main/Levelsanity/Level 2-9"},
    [0xD05] = {"@Main/Levelsanity/Level 2-9"},
    [0xD06] = {"@Main/Levelsanity/Level 2-9"},
    [0xD07] = {"@Main/Levelsanity/Level 2-9"},
    [0xD08] = {"@Main/Levelsanity/Level 2-9"},
    [0xD09] = {"@Main/Levelsanity/Level 2-9"},
    [0xD10] = {"@Main/Levelsanity/Level 10+"},
    [0xD11] = {"@Main/Levelsanity/Level 10+"},
    [0xD12] = {"@Main/Levelsanity/Level 10+"},
    [0xD13] = {"@Main/Levelsanity/Level 10+"},
    [0xD14] = {"@Main/Levelsanity/Level 10+"},
    [0xD15] = {"@Main/Levelsanity/Level 10+"},
    [0xD16] = {"@Main/Levelsanity/Level 10+"},
    [0xD17] = {"@Main/Levelsanity/Level 10+"},
    [0xD18] = {"@Main/Levelsanity/Level 10+"},
    [0xD19] = {"@Main/Levelsanity/Level 10+"},
    [0xD20] = {"@Main/Levelsanity/Level 10+"},
    [0xD21] = {"@Main/Levelsanity/Level 10+"},
    [0xD22] = {"@Main/Levelsanity/Level 10+"},
    [0xD23] = {"@Main/Levelsanity/Level 10+"},
    [0xD24] = {"@Main/Levelsanity/Level 10+"},
    [0xD25] = {"@Main/Levelsanity/Level 10+"},
    [0xD26] = {"@Main/Levelsanity/Level 10+"},
    [0xD27] = {"@Main/Levelsanity/Level 10+"},
    [0xD28] = {"@Main/Levelsanity/Level 10+"},
    [0xD29] = {"@Main/Levelsanity/Level 10+"},
    [0xD30] = {"@Main/Levelsanity/Level 10+"},
    [0xE20] = {"@Main/Hauksness/Erdrick's Armor"},
    [0xE40] = {"@Main/Kol/Fairy Flute"},
    [0xE80] = {"@Main/world_map/Erdrick's Token"},
    [0x4010D] = {"@Main/Tantagel Castle/Tantegel Castle - Gold Chest 1"},
    [0x4010F] = {"@Main/Tantagel Castle/Tantegel Castle - Gold Chest 2"},
    [0x4020E] = {"@Main/Tantagel Castle/Tantegel Castle - Gold Chest 3"},
    [0x4030F] = {"@Main/Tantagel Castle/Tantegel Castle - Gold Chest 4"},
    [0x50304] = {"@Main/Tantagel Castle/Return Gwaelin to Castle"},
    [0x50404] = {"@Main/Tantagel Castle/Throne Room - Gold Chest"},
    [0x50504] = {"@Main/Tantagel Castle/Throne Room - Torch Chest"},
    [0x50601] = {"@Main/Tantagel Castle/Throne Room - Key Chest"},
    [0x60B0B] = {"@Main/Charlock Castle/Dragonlord's Lair - Chest 1"},
    [0x60B0C] = {"@Main/Charlock Castle/Dragonlord's Lair - Chest 2"},
    [0x60B0D] = {"@Main/Charlock Castle/Dragonlord's Lair - Chest 3"},
    [0x60C0C] = {"@Main/Charlock Castle/Dragonlord's Lair - Chest 4"},
    [0x60C0D] = {"@Main/Charlock Castle/Dragonlord's Lair - Chest 5"},
    [0x60D0D] = {"@Main/Charlock Castle/Dragonlord's Lair - Chest 6"},
    [0x90805] = {"@Main/Garinham/Garinham - Chest 1"},
    [0x90806] = {"@Main/Garinham/Garinham - Chest 2"},
    [0x90905] = {"@Main/Garinham/Garinham - Chest 3"},
    [0xB1817] = {"@Main/Rimuldar/Rimuldar - Inn Chest"},
    [0xC0405] = {"@Main/Tantagel Castle/Stones of Sunlight"},
    [0xD0304] = {"@Main/world_map/Staff of Rain"},
    [0x100505] = {"@Main/Charlock Castle/Erdrick's Sword"},
    [0x150513] = {"@Main/Swamp Cave/Rescue Princess Gwaelin"},
    [0x160D05] = {"@Main/Mountain Cave/Mountain Cave - Level 1 - Chest"},
    [0x170106] = {"@Main/Mountain Cave/Mountain Cave - Level 2 - Chest 1"},
    [0x170202] = {"@Main/Mountain Cave/Mountain Cave - Level 2 - Chest 3"},
    [0x170302] = {"@Main/Mountain Cave/Mountain Cave - Level 2 - Chest 2"},
    [0x170A09] = {"@Main/Mountain Cave/Mountain Cave - Level 2 - Chest 4"},
    [0x180B00] = {"@Main/Garin's Grave/Garin's Grave - Level 1 - Chest 1"},
    [0x180C00] = {"@Main/Garin's Grave/Garin's Grave - Level 1 - Chest 2"},
    [0x180D00] = {"@Main/Garin's Grave/Garin's Grave - Level 1 - Chest 3"},
    [0x1A0101] = {"@Main/Garin's Grave/Garin's Grave - Level 3 - Chest 1"},
    [0x1A0D06] = {"@Main/Garin's Grave/Garin's Grave - Level 3 - Chest 2"},
    [0x1D0903] = {"@Main/Erdrick's Cave/Erdrick's Tablet"},
	[0xDEF00] = {"@Main/Monstersanity/Defeat Slime"},
	[0xDEF02] = {"@Main/Monstersanity/Defeat Red Slime"},
	[0xDEF04] = {"@Main/Monstersanity/Defeat Drakee"},
	[0xDEF0A] = {"@Main/Monstersanity/Defeat Magidrakee"},
	[0xDEF0C] = {"@Main/Monstersanity/Defeat Scorpion"},
	[0xDEF06] = {"@Main/Monstersanity/Defeat Ghost"},
	[0xDEF08] = {"@Main/Monstersanity/Defeat Magician"},
	[0xDEF0E] = {"@Main/Monstersanity/Defeat Druin"},
	[0xDEF10] = {"@Main/Monstersanity/Defeat Poltergeist"},
	[0xDEF12] = {"@Main/Monstersanity/Defeat Droll"},
	[0xDEF14] = {"@Main/Monstersanity/Defeat Drakeema"},
	[0xDEF16] = {"@Main/Monstersanity/Defeat Skeleton"},
	[0xDEF18] = {"@Main/Monstersanity/Defeat Warlock"},
	[0xDEF3C] = {"@Main/Monstersanity/Defeat Green Dragon"},
	[0xDEF42] = {"@Main/Monstersanity/Defeat Axe Knight"},
	[0xDEF1A] = {"@Main/Monstersanity/Defeat Metal Scorpion"},
	[0xDEF1C] = {"@Main/Monstersanity/Defeat Wolf"},
	[0xDEF1E] = {"@Main/Monstersanity/Defeat Wraith"},
	[0xDEF24] = {"@Main/Monstersanity/Defeat Wolflord"},
	[0xDEF32] = {"@Main/Monstersanity/Defeat Goldman"},
	[0xDEF20] = {"@Main/Monstersanity/Defeat Metal Slime"},
	[0xDEF22] = {"@Main/Monstersanity/Defeat Specter"},
	[0xDEF26] = {"@Main/Monstersanity/Defeat Druinlord"},
	[0xDEF28] = {"@Main/Monstersanity/Defeat Drollmagi"},
	[0xDEF2A] = {"@Main/Monstersanity/Defeat Wyvern"},
	[0xDEF2C] = {"@Main/Monstersanity/Defeat Rogue Scorpion"},
	[0xDEF2E] = {"@Main/Monstersanity/Defeat Wraith Knight"},
	[0xDEF34] = {"@Main/Monstersanity/Defeat Knight"},
	[0xDEF36] = {"@Main/Monstersanity/Defeat Magiwyvern"},
	[0xDEF38] = {"@Main/Monstersanity/Defeat Demon Knight"},
	[0xDEF3A] = {"@Main/Monstersanity/Defeat Werewolf"},
	[0xDEF3E] = {"@Main/Monstersanity/Defeat Starwyvern"},
	[0xDEF40] = {"@Main/Monstersanity/Defeat Wizard"},
	[0xDEF44] = {"@Main/Monstersanity/Defeat Blue Dragon"},
	[0xDEF46] = {"@Main/Monstersanity/Defeat Stoneman"},
	[0xDEF48] = {"@Main/Monstersanity/Defeat Armored Knight"},
	[0xDEF4A] = {"@Main/Monstersanity/Defeat Red Dragon"},
	[0xDEF30] = {"@Main/Monstersanity/Defeat Golem"},
	[0xDEF4C] = {"@Main/Monstersanity/Defeat Dragonlord 1"},
	[0xDEF4E] = {"@Main/Monstersanity/Defeat Dragonlord 2"},


}

return LOCATION_MAPPING
